### ISSUE TITLE
dependencies for `.ci/gitlab/template.ci.py` missing

### ISSUE THREAD

**Issue by ftalbrecht** [pymor/docker#83]
I can't `pip install dotenv` within the virtualenv on my machiine, so I tried to `make dorcker_run` and then execute `.ci/gitlab/template.ci.py`. However, the required dependencies are not installed within the container. I think it would make sense to have these installe. Opinions, @renefritze

**Comment by renefritze** [comment]
The package name is `python-dotenv`, `dotenv` is an apparently abandoned python2 only project. 
As for installing the deps in images here, [that's already the case](https://docs.pymor.org/2020-2-2/developer_docs.html#gitlab-ci). Not in every image though, only the sanity one (cause that's tiny and always the first to be updated in CI)

**Comment by ftalbrecht** [comment]
On 16.09.21 13:21, René Fritze wrote:
> The package name is `python-dotenv`, `dotenv` is an apparently abandoned python2 only project.

Ah, makes sense.

> As for installing the deps in images here, [that's already the case](https://docs.pymor.org/2020-2-2/developer_docs.html#gitlab-ci). Not in every image though, only the sanity one (cause that's tiny and always the first to be updated in CI)

Not that I went over these docs last week :/

I should read more carefully, thx!
